### ISSUE TITLE
Allow Turbine to produce outputs even if the simulation fails or produces errors

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/turb_sci_gate#15]
We would like for Turbine to be able to produce the outputs from Aspen Plus even if the Aspen Plus simulation produces errors.

**Comment by ksbeattie** [comment]
@fsoepyan is this something you feel is needed for FOQUS, say in the April release?

**Comment by fsoepyan** [comment]
@ksbeattie: The reason I opened this issue is because I am working on a project that involves using FOQUS to run multiple Aspen and Excel models.

One of the Aspen models is very complex. Running it may produce errors, but the model can still produce the outputs anyway.

If possible, we would like to have Turbine provide the outputs to FOQUS if the Aspen model produces these outputs, even if the model produces errors.

**Comment by eslickj** [comment]
I don't think we need this anymore.  I understand why it can help, but attempting to sort out whether the results of a failed simulation are meaningful is almost impossible in general.  I'm going to close this.  We can open a new issue if there is a compelling need in the future.
