### ISSUE TITLE
Provide option for Turbine to not shut down Aspen when it fails

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/turb_sci_gate#16]
We would like to have the option where Turbine does not shut down an Aspen simulation if the Aspen simulation produces errors, to give us the opportunity to study the Aspen file.

**Comment by ksbeattie** [comment]
@fsoepyan is this something you feel is needed for FOQUS, say in the April release?

**Comment by fsoepyan** [comment]
@ksbeattie: I opened this issue for similar reasons as issue #15, where if the Aspen model produces errors, we would like to be able to keep the Aspen file open, to see where the errors occured.

However, issue #15 has higher priority compared to this issue.

**Comment by ksbeattie** [comment]
Closing this as it is not a really pressing concern.  @fsoepyan says there is a work-around (saving the session right before it shuts down) though it is not documented (other than right here).
