### ISSUE TITLE
BFB AspenProperties No Licenses Available

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/turb_sci_gate#21]
# Details
Intermittently on AWS when opening BFB ACM simulation a call to the SLM server appears to fail and a dialog pops up that AspenProperties failed to get a license.  An AspenProperties process is running.  If one closes the dialog, another pops up asking to retry the connection.  If one hits 'yes' it will fail again and there is NO traffic recorded in the SLM Server logs.

# AspenTech Case
01832032 | SLM | Error while checking out license AspenProperties | Escalate Development | Urgent | 2019/10/30

# SLM Log
## ACM Opened Correctly 
```
PS C:\Users\Administrator> Get-Content 'C:\Program Files (x86)\AspenTech\SLMServerLogs\lserv.log' | select -Last 4
2 2 MjY3Mg== Fri Dec 06 18:52:28 2019  1575658348 SLM_AspenCustomModeler v 2 0 221 Administrator EC2AMAZ-V5K0UAA 8.6.1.0021 1 01:0:0:0:10.0.0.119:0:414:sim_server_36.0.0.249:6.2.9200_0_9_3:1033:1100:0 - - - - - 0 - - - NTc3OA== 142193 NjE5OTI0

2 2 MjY3Mg== Fri Dec 06 18:53:05 2019  1575658385 SLM_AspenCustomModeler v 0 1 0 Administrator EC2AMAZ-V5K0UAA 8.6.1.0021 1 01:0:0:0:10.0.0.119:0:414:sim_server_36.0.0.249:6.2.9200_0_9_3:1033:3972:0 - - - - - 0 - - - NTc3OQ== 309691 NDUxODg0

2 2 MjY3Mg== Fri Dec 06 18:53:05 2019  1575658385 SLM_LicenseProfile v 0 1 0 Administrator EC2AMAZ-V5K0UAA 8.6.1.0021 1 01:0:0:0:10.0.0.119:0:414:sim_server_36.0.0.249:6.2.9200_0_9_3:1033:3972:0 - - - - - 0 - - - NTc4MA== 467757 Nzc3NDQ4

2 2 MjY3Mg== Fri Dec 06 18:53:05 2019  1575658385 SLM_LicenseProfile v 2 0 0 Administrator EC2AMAZ-V5K0UAA 8.6.1.0021 1 01:0:0:0:10.0.0.119:0:414:sim_server_36.0.0.249:6.2.9200_0_9_3:1033:3972:0 - - - - - 0 - - - NTc4MQ== 466237 OTMzOTk0

PS C:\Users\Administrator>
```

## ACM Failed to get AspenProperties
Looks identical to `success`, if I close AspenProperties dialog next one gets a `Failed to establish connection.  Do you want to retry`.  If one hits `yes`, nothing additional is seen on SLM Server log and get AspenProperties dialog again.  In the background `AspenProperties` process hangs and eats up tons of CPU.
```
2 2 MjY3Mg== Fri Dec 06 20:06:21 2019  1575662781 SLM_AspenCustomModeler v 2 0 36 Administrator EC2AMAZ-V5K0UAA 8.6.1.0021 1 01:0:0:0:10.0.0.119:0:414:sim_server_36.0.0.249:6.2.9200_0_9_3:1033:5488:0 - - - - - 0 - - - NTg4OA== 234618 MTIwMDIxMQ==

2 2 MjY3Mg== Fri Dec 06 20:06:27 2019  1575662787 SLM_AspenCustomModeler v 0 1 0 Administrator EC2AMAZ-V5K0UAA 8.6.1.0021 1 01:0:0:0:10.0.0.119:0:414:sim_server_36.0.0.249:6.2.9200_0_9_3:1033:5328:0 - - - - - 0 - - - NTg4OQ== 929457 MTE2
NDA3NQ==
2 2 MjY3Mg== Fri Dec 06 20:06:28 2019  1575662788 SLM_LicenseProfile v 0 1 0 Administrator EC2AMAZ-V5K0UAA 8.6.1.0021 1 01:0:0:0:10.0.0.119:0:414:sim_server_36.0.0.249:6.2.9200_0_9_3:1033:5328:0 - - - - - 0 - - - NTg5MA== 409017 MTMzODQ3NA==

2 2 MjY3Mg== Fri Dec 06 20:06:28 2019  1575662788 SLM_LicenseProfile v 2 0 0 Administrator EC2AMAZ-V5K0UAA 8.6.1.0021 1 01:0:0:0:10.0.0.119:0:414:sim_server_36.0.0.249:6.2.9200_0_9_3:1033:5328:0 - - - - - 0 - - - NTg5MQ== 154683 NTYzNzAw
PS C:\Users\Administrator>
```
### ACM Failed to get AspenProperties
 If one hits `no` get series of dialogs one from `Physical Properties` says `Unable to generate aprpdf file using saved Aspen Properties`, then if I wait I get another `Physical Properties Configuration` dialog.

<img width="393" alt="Screen Shot 2019-12-06 at 10 48 34 AM" src="https://user-images.githubusercontent.com/738295/70350353-77b8ba00-181b-11ea-86f6-92d00be52adf.png">
<img width="1136" alt="Screen Shot 2019-12-06 at 11 01 33 AM" src="https://user-images.githubusercontent.com/738295/70350363-7a1b1400-181b-11ea-9725-98c8b564a86a.png">

<img width="411" alt="Screen Shot 2019-12-06 at 11 25 27 AM" src="https://user-images.githubusercontent.com/738295/70350301-548e0a80-181b-11ea-933f-1e5f5e1d7bcf.png">
<img width="487" alt="Screen Shot 2019-12-06 at 11 23 35 AM" src="https://user-images.githubusercontent.com/738295/70350303-56f06480-181b-11ea-9e3a-a139ffb5c2b6.png">

**Comment by boverhof** [comment]
# ACM BFB Success Open 
Group of AspenProperties files in the ACM Folder.
<img width="901" alt="Screen Shot 2019-12-06 at 11 46 47 AM" src="https://user-images.githubusercontent.com/738295/70351661-4ab9d680-181e-11ea-8151-17ca1f3dc11c.png">
# ACM BFB Failure to Open
Empty directory

**Comment by boverhof** [comment]
# Switch SLM to `dudley.lbl.gov`
This did not help, same intermittent problem with AspenProperties.
<img width="1549" alt="Screen Shot 2019-12-08 at 10 17 55 AM" src="https://user-images.githubusercontent.com/738295/70393966-0a389500-19a5-11ea-9568-69b7cb8b7e27.png">

**Comment by boverhof** [comment]
# Wireshark shows on correct behavior UDP exchange:

<img width="1078" alt="Screen Shot 2019-12-09 at 11 23 14 AM" src="https://user-images.githubusercontent.com/738295/70465726-6ddec300-1a76-11ea-8c8f-e84c20cbf438.png">

**Comment by boverhof** [comment]
# Wireshark broken exchange resulting in AspenProperties error

<img width="1079" alt="Screen Shot 2019-12-09 at 11 23 54 AM" src="https://user-images.githubusercontent.com/738295/70465771-86e77400-1a76-11ea-81d1-2ee73c52d7b4.png">

**Comment by ksbeattie** [comment]
@boverhof is asking for @fsoepyan & @eslickj to try and reproduce this in their environments...

**Comment by ksbeattie** [comment]
@boverhof says this is closed.
