### ISSUE TITLE
Assembly Binding Problem: VariableTree

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/turb_sci_gate#27]
# Description
Deployments of new SimSinter/TurbineLite releases are failing in SimSinter.  The VariableTree assembly is not found.  

## Detail 
Running AspenSinterConsumerConsole and submitting jobs.
### turbine job submit
```
(ccsi-foqus) C:\Users\Administrator\Desktop\turbine_client_test>more jobs_file.json
[{"Simulation": "BFB_sinter_config_v6",
  "Input": {}
}]
(ccsi-foqus) C:\Users\Administrator\Desktop\turbine_client_test>python \ProgramData\Anaconda3\envs\ccsi-foqus\Scripts\turbine_session_create turbine.cfg
8e7e9700-0c60-4d42-8a89-6649703a8081

(ccsi-foqus) C:\Users\Administrator\Desktop\turbine_client_test>python \ProgramData\Anaconda3\envs\ccsi-foqus\Scripts\turbine_session_append 8e7e9700-0c60-4d42-8a89-6649703a8081 jobs_file.json turbine.cfg
[2]

(ccsi-foqus) C:\Users\Administrator\Desktop\turbine_client_test>python \ProgramData\Anaconda3\envs\ccsi-foqus\Scripts\turbine_session_start 8e7e9700-0c60-4d42-8a89-6649703a8081 turbine.cfg
1

```

### AspenSinterConsumerConsole running
``
SinterConsumerConsole: >> Waiting 1
SinterConsumerConsole: Completed
SinterConsumerConsole: Stop called
SinterConsumerConsole: > New Task
SinterConsumerRun.Run: Starting
DBJobQueue.GetNext: Get Job for Application: ACM
top
DBJobQueue.GetNext: Get Job for Application: AspenPlus
SinterConsumerRun.Run: 9/8/2021 12:36:51 AM - No submitted jobs in queue
SinterConsumerConsole: >> Waiting 1
SinterConsumerConsole: Completed
SinterConsumerConsole: Stop called
SinterConsumerConsole: > New Task
SinterConsumerRun.Run: Starting
DBJobQueue.GetNext: Get Job for Application: ACM
top
DBJobQueue.GetNext: Found Job(b0f182c4-16dd-46fa-adc0-194fa1464a39): BFB_sinter_config_v6,ACM
SinterConsumerRun.Run: 9/8/2021 12:36:55 AM - Found JOB(reset): 2
SinterConsumerRun.Run: Setup Sinter Process 2
SinterConsumer: DoSetup Called on 2
ConsumerJobContract: Setup consumer GUID f37fa358-a318-495c-83a9-361b6d160ca0
SinterConsumerRun.SetupWorkingDir: The Working directory is: test\2
SinterConsumerRun.CopyFromCache: Copying From Cache: test\a0308275-770f-4845-872f-d6e0f3eb25df
SinterConsumerRun.CopyFromCache: Directory test\a0308275-770f-4845-872f-d6e0f3eb25df doesn't exist
ConsumerJobContract: FILE: configuration
ConsumerJobContract: FILE: BFBv6.2.acmf
ConsumerJobContract: FILE: aspenfile
AspenSinterConsumer.copyFilesToDisk: file_version: 0.3
ConsumerJobContract: FILE: configuration
ConsumerJobContract: FILE: BFBv6.2.acmf
ConsumerJobContract: FILE: aspenfile
ConsumerJobContract: FILE: configuration
ConsumerJobContract: FILE: BFBv6.2.acmf
SinterConsumerConsole: >> Waiting 1
top
ConsumerJobContract: FILE: aspenfile
SinterConsumer.DoConfigure: Attempt to Read test\2\sinter_configuration.txt
SinterConsumer.DoConfigure.InitializeSinter: Could not load file or assembly 'VariableTree, Version=1.6.0.0, Culture=neutral, PublicKeyToken=4be585aca2084488' or one of its dependencies. The system cannot find the file specified.
SinterConsumer.DoConfigure.InitializeSinter:    at sinter.sinter_Sim..ctor()
   at sinter.sinter_InteractiveSim..ctor() in c:\Users\Administrator\Documents\Visual Studio 2012\Projects\SimSinter\Master\Sinter\sinter_InteractiveSim.cs:line 21
   at sinter.sinter_SimACM..ctor() in c:\Users\Administrator\Documents\Visual Studio 2012\Projects\SimSinter\Master\Sinter\sinter_SimACM.cs:line 75
   at Turbine.Consumer.AspenTech.AspenSinterConsumer.InitializeSinter(IJobConsumerContract job, String workingDir, String config) in c:\Users\Administrator\Documents\Visual Studio 2012\Projects\turb_sci_gate\Master\Turbine.Consumer.AspenTech\AspenSinterConsumer.cs:line 152
   at Turbine.Consumer.SimSinter.SinterConsumerRun.DoConfigure(IJobConsumerContract job, IProcess process, Int32 maxAttemptsReadSetup) in c:\Users\Administrator\Documents\Visual Studio 2012\Projects\turb_sci_gate\Master\Turbine.Consumer.SimSinter\SinterConsumerRun.cs:line 455
SinterConsumerConsole: Exception caught from Run: One or more errors occurred.
SinterConsumerConsole:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
   at Turbine.Consumer.Console.SinterConsumerConsole.Run() in c:\Users\Administrator\Documents\Visual Studio 2012\Projects\turb_sci_gate\Master\Turbine.Consumer.Console\SinterConsumerConsole.cs:line 238
SinterConsumerConsole: InnerException: System.IO.FileNotFoundException: Could not load file or assembly 'VariableTree, Version=1.6.0.0, Culture=neutral, PublicKeyToken=4be585aca2084488' or one of its dependencies. The system cannot find the file specified.
File name: 'VariableTree, Version=1.6.0.0, Culture=neutral, PublicKeyToken=4be585aca2084488'
   at sinter.sinter_Sim..ctor()
   at sinter.sinter_InteractiveSim..ctor() in c:\Users\Administrator\Documents\Visual Studio 2012\Projects\SimSinter\Master\Sinter\sinter_InteractiveSim.cs:line 21
   at sinter.sinter_SimACM..ctor() in c:\Users\Administrator\Documents\Visual Studio 2012\Projects\SimSinter\Master\Sinter\sinter_SimACM.cs:line 75
   at Turbine.Consumer.AspenTech.AspenSinterConsumer.InitializeSinter(IJobConsumerContract job, String workingDir, String config) in c:\Users\Administrator\Documents\Visual Studio 2012\Projects\turb_sci_gate\Master\Turbine.Consumer.AspenTech\AspenSinterConsumer.cs:line 152
   at Turbine.Consumer.SimSinter.SinterConsumerRun.DoConfigure(IJobConsumerContract job, IProcess process, Int32 maxAttemptsReadSetup) in c:\Users\Administrator\Documents\Visual Studio 2012\Projects\turb_sci_gate\Master\Turbine.Consumer.SimSinter\SinterConsumerRun.cs:line 462
   at Turbine.Consumer.SimSinter.SinterConsumerRun.Run() in c:\Users\Administrator\Documents\Visual Studio 2012\Projects\turb_sci_gate\Master\Turbine.Consumer.SimSinter\SinterConsumerRun.cs:line 948
   at Turbine.Consumer.Console.SinterConsumerConsole.<Run>b__4() in c:\Users\Administrator\Documents\Visual Studio 2012\Projects\turb_sci_gate\Master\Turbine.Consumer.Console\SinterConsumerConsole.cs:line 176
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

SinterConsumerConsole: Stop called
SinterConsumerConsole: > New Task
SinterConsumerRun.Run: Starting
DBJobQueue.GetNext: Get Job for Application: ACM
top
DBJobQueue.GetNext: Get Job for Application: AspenPlus
SinterConsumerRun.Run: 9/8/2021 12:36:58 AM - No submitted jobs in queue
SinterConsumerConsole: >> Waiting 1
SinterConsumerConsole: Completed
SinterConsumerConsole: Exit Unregister Consumer
ConsumerRegistrationContract: UnRegister Consumer f37fa358-a318-495c-83a9-361b6d160ca0
SinterConsumerConsole: lock consumer
SinterConsumerMonitor.Monitor: MonitorTerminated: Cancel Key Pressed
SinterConsumerMonitor: MonitorTerminate
SinterConsumerRun.Stop: Failure to Obtain Lock
SinterConsumerMonitor.MonitorTerminate: Wait for terminate to release lock on consumerRun
SinterConsumerConsole: Obtained ConsumerRun Lock: Monitor Terminate
SinterConsumerConsole: Consumer Exit
```

**Comment by boverhof** [comment]
# Strong Name Assembly VariableTree
```
C:\Program Files (x86)\Microsoft Visual Studio 11.0>sn.exe -T "\Program Files (x86)\CCSI\SimSinter\VariableTree.dll"

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.17929
Copyright (c) Microsoft Corporation.  All rights reserved.

Public key token is 4be585aca2084488

C:\Program Files (x86)\Microsoft Visual Studio 11.0>
```

**Comment by boverhof** [comment]
# VariableTree version
![Screen Shot 2021-09-07 at 4 47 52 PM](https://user-images.githubusercontent.com/738295/132424078-a774896a-c891-4ebc-9a72-cd0271f81fcd.png)

**Comment by boverhof** [comment]
# Add Runtime Assembly Location in XML Descriptor
```xml
<configuration>
  <configSections>
    <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
      <section name="Turbine.Console.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false"/>
    </sectionGroup>
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false"/>
    <section name="unity" type="Microsoft.Practices.Unity.Configuration.UnityConfigurationSection, Microsoft.Practices.Unity.Configuration"/>
  </configSections>

  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Sinter" publicKeyToken="4be585aca2084488"/>
        <codeBase version="2.1.0.0" href="FILE://C:\Program Files (x86)\CCSI\SimSinter\Sinter.dll"/>
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="VariableTree" publicKeyToken="4be585aca2084488"/>
        <codeBase version="1.6.0.0" href="FILE://C:\Program Files (x86)\CCSI\SimSinter\VariableTree.dll"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>

```

## Resulted in a `success`
```
(ccsi-foqus) C:\Users\Administrator\Desktop\turbine_client_test>python \ProgramData\Anaconda3\envs\ccsi-foqus\Scripts\turbine_job_script -bvj 4 turbine.cfg
          Id     4
        Guid     7c4dda9d-2d1a-4381-a19c-b18e0332ab9d
  Simulation     BFB_sinter_config_v6
       State     success
    Messages     ['event=setup,consumer=63d662b3-731e-4f0a-bc0d-9be816c4080b', 'working directory setup finished', 'sinter read setup finished', 'event=running,consumer=63d662b3-731e-4f0a-bc0d-9be816c4080b', 'sinter inputs sent, running simulation', 'Real Run was complete and successful.', 'event=sucess,consumer=63d662b3-731e-4f0a-bc0d-9be816c4080b']
       Input     {}
      Output     {'BFBadsT.Nx': {'value': 966.9414138472738, 'units': ''}, 'BFBadsM.Nx': {'value': 966.9414138472738, 'units': ''}, 'BFBadsB.Nx': {'value': 966.9414138472738, 'units': ''}, 'BFBrgnT.Nx': {'value': 10764.767212776445, 'units': ''}, 'BFBrgnB.Nx': {'value': 10764.767212776445, 'units': ''}, 'CMPads.J': {'value': 1758.491925093835, 'units': 'kW'}, 'CMPrgn.J': {'value': 195.97057550331508, 'units': 'kW'}, 'GHXfg.GasIn.P': {'value': 1.01325, 'units': 'bar'}, 'GHXcmp.GasIn.P': {'value': 1.01325, 'units': 'bar'}, 'CMPads.GasOut.P': {'value': 1.3466386487687048, 'units': 'bar'}, 'CMPrgn.GasOut.P': {'value': 1.2347079824532108, 'units': 'bar'}, 'GasOut.T': {'value': 73.517735643283, 'units': 'degC'}, 'GasOut.F': {'value': 5166.659346547, 'units': 'kmol/hr'}, 'rhos': {'value': 442.0, 'units': 'kg/m3'}, 'GHXfg.a_exch': {'value': 5749.664949290344, 'units': 'm2'}, 'GHXcmp.a_exch': {'value': 1688.5159415981639, 'units': 'm2'}, 'GHXfg.HXIn.F': {'value': 28737.646296741925, 'units': 'kmol/hr'}, 'GHXcmp.HXIn.F': {'value': 49782.12186921814, 'units': 'kmol/hr'}, 'CW_SHXlean.HXIn.F': {'value': 6516.972844237787, 'units': 'kmol/hr'}, 'BFBadsT.HXIn.F': {'value': 148040.73362238897, 'units': 'kmol/hr'}, 'BFBrgnT.HXIn.F': {'value': 1316.55215912462, 'units': 'kmol/hr'}, 'BFBrgnB.HXIn.F': {'value': 296.83815942395233, 'units': 'kmol/hr'}, 'removalH2O': {'value': 0.5911227435454254, 'units': ''}, 'removalCO2': {'value': 0.9164549276734546, 'units': ''}, 'LR_SHXlean.A_exch': {'value': 18732.538527879966, 'units': 'm2'}, 'LR_SHXrich.A_exch': {'value': 19143.346173926682, 'units': 'm2'}, 'CW_SHXlean.A_exch': {'value': 775.4665927756596, 'units': 'm2'}, 'BFBadsM.HXIn.F': {'value': 148040.6091328439, 'units': 'kmol/hr'}, 'BFBadsB.HXIn.F': {'value': 148040.69467301527, 'units': 'kmol/hr'}, 'status': {'units': '', 'value': 0}}
      Errors     []
      Status     0
     Session     8e7e9700-0c60-4d42-8a89-6649703a8081
  Initialize     False
       Reset     True
     Visible     False
    Consumer     63d662b3-731e-4f0a-bc0d-9be816c4080b
      Create     2021-09-08T07:59:03.7870000
      Submit     2021-09-08T07:59:10.5530000
       Setup     2021-09-08T07:59:12.2730000
     Running     2021-09-08T07:59:58.6200000
    Finished     2021-09-08T08:00:09.0870000
===================================
=  Basic Stats Job 4
===================================
               Queue -- 0:00:08.486000
               Setup -- 0:00:46.347000
             Runtime -- 0:00:10.467000
                Done
```

**Comment by boverhof** [comment]
Created Tag turb_sci_gate tag 2.3.0.1.  Added VARIABLETREE_HREF and put in runtime assembly reference for it and updated the version to 2.1.0.1 VariableTree.dll

**Comment by lbianchi-lbl** [comment]
This has been addressed by @boverhof and can be considered done.
